### PR TITLE
Fix stack

### LINKED ISSUE #7: Assertion 'Ensure the above chopping math was performed correctly.'
Running the following code leads to an error 'Line 7: Ensure the above chopping math was performed correctly.' when run in Firefox 111.0.1 in Windows 10 on an Intel(R) Core(TM) i7-8550U CPU:

```
ADDI $sp, $sp, -4
LUI $t1, 39612
ADDIU $t1, $t1, 57072
SW $t1, 0($sp)
```

Instead, the code should store the byte sequence 154, 188, 222, 240 on the stack, starting at $sp.

The problem seems to be with how JavaScript and ```stack.setDataAtAddress``` seem to handle signed/unsigned. In ```setDataAtAddress```, the input data is first converted to unsigned using ```signedNumberToUnsignedNumber```. Then, the given number of bits is chopped out by a binary. JavaScript will implicitly consider this a signed number, while the check ```assert(minValidValue <= data && data <= maxValidValue)``` - which leads to the message above - assumes an unsigned number.

In addition, I found that the right shift used to split up the value into bytes is an arithmetic right shift, which will duplicate the sign bit, introducing problems when working with unsigned numbers. It seems that a logical right shift (```>>>```) would be in order here.

I will provide a pull request with a fix.

### PR DESCRIPTION
**Pull request by ralfgerlich**
Closes #7

### CODE REVIEW

**Comment by ericwooley** [comment]
Hi @ralfgerlich 

I'm not sure why there is so much interest in this project recently. 

This was just a school project a friend and I made in college, in like 2013. It's been so long, I really don't remember how it works very well, nor do I really even remember all the specifics of working with assembly all that well.

It looks like you have been doing lots of work on this project. Would you like to be added as a maintainer?

**Comment by ralfgerlich** [comment]
You may not know it, but your simulator is being used as a teaching tool in courses in at least two universities in Southwest Germany (Baden Wuerttemberg State Cooperative University in Stuttgart and in Friedrichshafen). As I prepare to take over teaching one of those courses, I have been having a look at the simulator and found some things that still needed to be done or would be worthwhile to add. This is the main reason for the recent activity.

I do maintain my own fork, but I would love to become a maintainer on the original.

**Comment by ericwooley** [comment]
Great, thanks @ralfgerlich I invited you as a collaborator. 

I am in the middle of a vacation, but I'll put some love into this project when I get back. Get the dependencies updated, online hosting via github, etc....

**Comment by ralfgerlich** [comment]
@ericwooley Thank you for the invitation. I will handle the pull-requests I created myself in that case.

Clearly, you can feel free to perform the updates you listed, but only if you want to do them.

For my use-case the primary intent is to complete the integer-instructions, add some ease-of-use features, complete the tests and fix some bugs for stability. I have already done most of that. I have also hosted the application on my own webserver for the course.

**Pull request merged**
